apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-volume
  labels:
    app: kafka
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
     namespace: kafka
     name: data-my-release-kafka-0
  hostPath:
    path: "/bitnami/kafka"