apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv-volume
  labels:
    app: zookeeper
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
     namespace: kafka
     name: data-my-release-zookeeper-0
  hostPath:
    path: "/bitnami/zookeeper"